# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/v2a-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter v2awifi,$(TARGET_DEVICE)),)

endif
